### ISSUE TITLE
Slight error in Docker example code

### ISSUE THREAD

**Issue by chrisdukey** [jtfrey/xdmod-container#1]
Thanks for the docker container, you've saved me from trying to build xdmod on Ubuntu (nightmare!). Just a note for anyone like me who is not overly familiar with docker. In the example section where you're building the container there's a small error in the example code. It's missing the full stop that indicates that the docker file is in the current directory. 

```
$ cd Docker
$ ROOT_PASSWORD="<password>" docker build --rm --tag local/xdmod:8.1.2 .
```

**Comment by jtfrey** [comment]
Thanks for letting me know, should be fixed in the README.md now.
